// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvvujlwhsypzkulnnzhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2dnVqbHdoc3lwemt1bG5uemhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDU1NzIsImV4cCI6MjA2MzY4MTU3Mn0.XFC6aw_Q3efH_KoZKrz1g7ARdZpNe1FB6SmrQWvnWYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);